version: '2'
services:
    nginx:
        build:
            context: nginx
        links:
            - php
    php:
        build:
            context: php
        ports:
            - "587:587" # SMTP
