version: '2'
services:
    nginx:
        ports:
            - "80:80"
        volumes:
            - "../www:/var/www"
            - "./nginx/dev-default.conf:/etc/nginx/conf.d/default.conf"
        restart: always
        hostname: dev-nginx
        links:
            - php
    php:
        domainname: dev.api.pixelstairs.com
        volumes:
            - "../www:/var/www"
        working_dir: /var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=dev.rds.pixelstairs.com"
        restart: always
        hostname: dev-php
        command: sh /var/entrypoint/api-dev.sh
