version: '2'
services:
    nginx:
        ports:
            - "80:80"
        volumes:
            - "../www:/var/www"
        restart: always
        hostname: dev-nginx
    php:
        domainname: dev.api.pixelstairs.com
        volumes:
            - "../api:/var/www"
        working_dir: /var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=rdsdev.pixelstairs.com"
        restart: always
        hostname: dev-php
        command: sh /var/entrypoint/api-dev.sh
