version: '2'
services:
    nginx:
        ports:
            - "80:80"
        volumes:
            - "../api:/var/www"
            - "./nginx/local-default.conf:/etc/nginx/conf.d/default.conf"
        restart: always
        hostname: local-nginx
        links:
            - php
    php:
        domainname: local.api.pixelstairs.com
        volumes:
            - "../api:/var/www"
        working_dir: /var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
        links:
            - database
        ports:
            - "2525:2525" # SMTP - mailtrap
        restart: always
        hostname: local-php
        command: sh /var/entrypoint/api-local.sh
    database:
        build:
            context: mariadb
        ports:
            - "33061:3306"
        volumes:
            - ./mariadb/database:/var/lib
        restart: always
        hostname: local-database
