version: '2'
services:
    nginx:
        ports:
            - "80:80"
        volumes:
            - "../www:/var/www"
            - "./nginx/prod-default.conf:/etc/nginx/conf.d/default.conf"
        restart: always
        hostname: prod-nginx
        links:
            - php
            - sentry
    php:
        domainname: api.pixelstairs.com
        volumes:
            - "../www:/var/www"
        working_dir: /var/www
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=rds.pixelstairs.com"
        restart: always
        hostname: prod-php
        command: sh /var/entrypoint/api-prod.sh
